server:
  port: 9000

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  rabbitmq:
    host: 192.168.1.23
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    order-service: /api-gateway/order/**
    product-service: /api-gateway/product/**
  ignored-patterns: /*-service/**
  sensitive-headers:
  
env: dev
branch: master