server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000

zuul:
  routes:
    order-service: /api-gateway/order/**
    product-service: /api-gateway/product/**
  ignored-patterns: /*-service/**
  sensitive-headers:
  
env: test
branch: master