server:
  port: 8781

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env: dev
branch: master