server:
  port: 8771


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
      
env: dev
branch: master