server:
  port: 8771

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.1.23
    port: 5672
    username: guest
    password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env: devbgy
branch: master